# Generated by Django 3.1.6 on 2021-02-09 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
